#!/bin/bash

apt-get update
apt-get install epstool nettle-bin nettle-dev units librsb-dev libpcre3-dev texlive-base texlive-latex-recommended texlive-xetex texlive-extra-utils texlive-formats-extra texlive-latex-extra texlive-plain-generic gnuplot-qt libmgl-qt5-7.5.0 libplplotqt2 libqscintilla2-qt5-13 libqscintilla2-qt5-dev libqscintilla2-qt5-l10n libqt5bluetooth5-bin libqt5bluetooth5 libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5designercomponents5 libqt5gui5 libqt5help5 libqt5location5-plugins libqt5location5 libqt5network5 libqt5nfc5 libqt5opengl5-dev libqt5opengl5 libqt5positioning5-plugins libqt5positioning5 libqt5positioningquick5 libqt5printsupport5 libqt5qml5 libqt5quick5 libqt5quickcontrols2-5 libqt5quickparticles5 libqt5quicktemplates2-5 libqt5quicktest5 libqt5quickwidgets5 libqt5sensors5-dev libqt5sensors5 libqt5serialport5-dev libqt5serialport5 libqt5sql5-ibase libqt5sql5-mysql libqt5sql5-odbc libqt5sql5-psql libqt5sql5-sqlite libqt5sql5-tds libqt5sql5 libqt5svg5-dev libqt5svg5 libqt5test5 libqt5waylandclient5 libqt5webchannel5-dev libqt5webchannel5 libqt5webengine-data libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libqt5webkit5 libqt5websockets5-dev libqt5websockets5 libqt5webview5-dev libqt5webview5 libqt5widgets5 libqt5x11extras5-dev libqt5x11extras5 libqt5xml5 libqt5xmlpatterns5-dev libqt5xmlpatterns5 libqtermwidget5-0 lxqt-system-theme lxqt-themes plplot-driver-qt qdbus-qt5 qdoc-qt5 qml-module-qt-labs-calendar qml-module-qt-labs-folderlistmodel qml-module-qt-labs-location qml-module-qt-labs-platform qml-module-qt-labs-settings qml-module-qt-labs-sharedimage qml-module-qt-websockets qml-module-qtbluetooth qml-module-qtgraphicaleffects qml-module-qtlocation qml-module-qtnfc qml-module-qtpositioning qml-module-qtqml-models2 qml-module-qtqml-statemachine qml-module-qtquick-controls2 qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-extras qml-module-qtquick-layouts qml-module-qtquick-localstorage qml-module-qtquick-particles2 qml-module-qtquick-privatewidgets qml-module-qtquick-shapes qml-module-qtquick-templates2 qml-module-qtquick-window2 qml-module-qtquick-xmllistmodel qml-module-qtquick2 qml-module-qtsensors qml-module-qttest qml-module-qtwebchannel qml-module-qtwebengine qml-module-qtwebsockets qml-module-qtwebview qt5-assistant qt5-default qt5-flatpak-platformtheme qt5-gtk-platformtheme qt5-qmake-bin qt5-qmake qt5-qmltooling-plugins qt5-style-kvantum-themes qt5-style-kvantum qt5serialport-examples qtbase5-dev-tools qtbase5-dev qtbase5-doc-html qtbase5-doc qtbase5-examples qtbase5-private-dev qtchooser qtconnectivity5-dev qtconnectivity5-doc-html qtconnectivity5-doc qtconnectivity5-examples qtdeclarative5-dev-tools qtdeclarative5-dev qtdeclarative5-doc-html qtdeclarative5-doc qtdeclarative5-examples qtdeclarative5-private-dev qterminal qtermwidget5-data qtgraphicaleffects5-doc-html qtgraphicaleffects5-doc qtlocation5-dev qtlocation5-doc-html qtlocation5-doc qtlocation5-examples qtpositioning5-dev qtquickcontrols2-5-dev qtquickcontrols2-5-doc-html qtquickcontrols2-5-doc qtquickcontrols2-5-examples qtquickcontrols5-doc-html qtquickcontrols5-doc qtquickcontrols5-examples qtsensors5-doc-html qtsensors5-doc qtsensors5-examples qtserialport5-doc-html qtserialport5-doc qtsvg5-doc-html qtsvg5-doc qtsvg5-examples qttools5-dev-tools qttools5-dev qttools5-doc-html qttools5-doc qttools5-examples qttools5-private-dev qtwebchannel5-doc-html qtwebchannel5-doc qtwebchannel5-examples qtwebengine5-dev-tools qtwebengine5-dev qtwebengine5-doc-html qtwebengine5-doc qtwebengine5-examples qtwebengine5-private-dev qtwebsockets5-doc-html qtwebsockets5-doc qtwebsockets5-examples qtwebview5-doc-html qtwebview5-doc qtwebview5-examples qtx11extras5-doc-html qtx11extras5-doc qtxmlpatterns5-dev-tools qtxmlpatterns5-doc-html qtxmlpatterns5-doc qtxmlpatterns5-examples build-essential gcc g++ gfortran make libblas-dev liblapack-dev libpcre3-dev libarpack2-dev libcurl4-openssl-dev epstool libfftw3-dev transfig libfltk1.3-dev libfontconfig1-dev libfreetype6-dev libgl2ps-dev libglpk-dev libreadline-gplv2-dev gnuplot libgraphicsmagick++1-dev libhdf5-serial-dev openjdk-12-jdk libsndfile1-dev llvm-dev texinfo libgl1-mesa-dev libosmesa6-dev pstoedit portaudio19-dev libjack-dev libqhull-dev libqrupdate-dev libqscintilla2-qt5-dev libsuitesparse-dev texlive libxft-dev zlib1g-dev autoconf automake bison flex gperf gzip icoutils librsvg2-bin libtool rsync tar perl liblapacke-dev libopenblas-dev libmkl-full-dev libsundials-dev
apt-get clean

# Buggy GPU driver workaround
echo "# Generated by driver (for use by libtool)" > /usr/lib/x86_64-linux-gnu/libGL.la
echo "dlname='libGL.so'" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "library_names='libGL.so.1 libGL.so'" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "dependency_libs=' -L/usr/X11R6/lib -lm -lXext -lX11 -ldl'" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "current=1" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "age=0" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "revision=1" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "installed=yes" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "dlopen=''" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "dlpreopen=''" >> /usr/lib/x86_64-linux-gnu/libGL.la
echo "libdir='/usr/lib/x86_64-linux-gnu/'" >> /usr/lib/x86_64-linux-gnu/libGL.la

ldconfig
export CPPFLAGS="-I /usr/include/suitesparse"
export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libGL.so"
./bootstrap
mkdir build
cd build
../configure && make -j8 V=1 && make install V=1 && cd .. && rm -Rfv build/

exit 0
